---
# Parámetros específicos del rol dhcpd
dhcp_interface: "eth1"
dhcp_range_start: "192.168.100.100"
dhcp_range_end: "192.168.100.200"
dhcp_default_lease_time: 600
dhcp_max_lease_time: 7200
dhcp_router: "192.168.100.1"
dhcp_dns_servers:
  - "192.168.100.10"
dhcp_domain_name: "{{ lab_domain }}"

dhcp_static_hosts: []
# Ejemplo de host reservado:
# dhcp_static_hosts:
#   - name: "server-fijo"
#     mac: "08:00:27:aa:bb:cc"
#     ip: "192.168.100.50"
