---
- name: Configurar y validar servicio BIND9 (DNS)
  hosts: dns_servers
  become: true
  roles:
    - bind9

- name: Configurar y validar servicio DHCPD
  hosts: dhcp_servers
  become: true
  roles:
    - dhcpd
